### ISSUE TITLE
Why do we use custom Value Label on the optionCell

### ISSUE THREAD

**Issue by zhigang1992** [romaonthego/RETableViewManager#180]
Why not use the DetailedLabel????

Things like this happened 

:sob: 

![messages_image_993987839_](https://cloud.githubusercontent.com/assets/1057756/3367053/c046cb62-fb53-11e3-858f-67d5d39b2e40.png)

**Comment by natan** [comment]
+1. This also results in the value label having the wrong highlight color on >= iOS 7 (white vs none).
