### ISSUE TITLE
Regression since 1.5.13

### ISSUE THREAD

**Issue by skrew** [romaonthego/RETableViewManager#208]
When you make a simple list with a style like ```UITableViewCellStyleSubtitle``` only the first cell have the good style. I think it's because you mix up new apis since iOS 6 and olders.

You can fix this bug by removing this line in ```RETableViewManager.m``` line 217:
```[self.tableView registerClass:cellClass forCellReuseIdentifier:cellIdentifier];```

Tell me if you want a PR

**Comment by romaonthego** [comment]
Fixed, thanks
