### ISSUE TITLE
Not work in swift.

### ISSUE THREAD

**Issue by ondev** [romaonthego/RETableViewManager#210]
Class cellClass = [self classForCellAtIndexPath:indexPath];

cellClass always return nil.

**Comment by ondev** [comment]
I got it, when pass string from swift,  the string Class is Swift._NSContiguousString,  so need add more Default class in - (void)registerDefaultClasses

self[@"Swift._NSContiguousString"] = @"RETableViewCell";

**Comment by romaonthego** [comment]
Yeah, Swift is not supported as of now. I will consider it for a future release.

**Comment by jianghaoyuan2007** [comment]
I also met this similar question, for example: Item class '%@' does not exist. so I search it on Google, and  It is OK now. I need add a extra code
@objc (TSMutilineTextItemCell)
class TSMutilineTextItemCell: RETableViewCell {

**Comment by neil-wu** [comment]
hope for swift suppored

**Comment by thankmelater23** [comment]
Is it possible to use this in a swift program?

**Comment by neil-wu** [comment]
Now I use it in my swift project. works well.

**Comment by thankmelater23** [comment]
Which steps do I have to take?
