### ISSUE TITLE
Retain cycle through delegate

### ISSUE THREAD

**Issue by sebastianludwig** [romaonthego/RETableViewManager#237]
The delegate property of `RETableViewManager` should be `weak` instead of `assign` (as delegates should always be). This way it's a retain cycle and any view controller using a `RETableViewManager` won't ever be deallocated (without taking extra actions).

**Comment by ericertl** [comment]
:+1:

**Comment by sebastianludwig** [comment]
My bad, of course `assign` does _not_ create a retain cycle but the delegate property should be `weak` anyway to prevent dangling pointers.
