### ISSUE TITLE
TextItem display incorrectly on iPad

### ISSUE THREAD

**Issue by ajurcevic** [romaonthego/RETableViewManager#249]
Hi guys, I'm having issues with displaying the RETextItem correctly on iPad.

deployment target for 8.1, however only noticing on iOS9+ devices.

using this line to display:
[RETextItem itemWithTitle:@"Version" value:@"1.8.5"]

but i am getting indentations of the heading and Title, the value however appears to stay put...

Landscape:
![Image of Landscape](http://s24.postimg.org/jv2srubc5/landscape1.png)
Portrait:
![Image of Portrait](http://s3.postimg.org/jz31m6ner/portrait1.png)

**Comment by loadmemo** [comment]
you can fix it with code below
// iOS9+
    if([self.tableView respondsToSelector:@selector(setCellLayoutMarginsFollowReadableWidth:)]) {
        self.tableView.cellLayoutMarginsFollowReadableWidth = NO;
    }

**Comment by ajurcevic** [comment]
closing as the above code from loadmemo fixed this at the time.
