### ISSUE TITLE
More maintainers

### ISSUE THREAD

**Issue by sebastianludwig** [romaonthego/RETableViewManager#253]
I love this library, but the maintenance frequency is pretty poor (last merge 7 month ago, last commit 11 month ago). I understand that one might not always have as much time to maintain a project as one had when starting it. However a project with more than 1800 stars deserves better. Maybe it's time to elect someone as co-maintainer? I'd love to see RETableViewManager evolve further over time - too much work went already into it, to let it slowly decay. And we just don't need someone else starting over from scratch "because this project seems dead".

**Comment by XBeg9** [comment]
I am new maintainer. Don't hesitate to file new issue if you find something. Thanks. @sebastianludwig
