### ISSUE TITLE
How to get callback for each text entered in RETextItem so that we can process on that text

### ISSUE THREAD

**Issue by ProAjit** [romaonthego/RETableViewManager#258]
Hi, Thanks for wonderful library. 
I have one quick query. I searched a lot but couldn't find the solution to allow only certain characters in my RETextItem, like we achieve it in delegate shouldChangeCharactersInRange for UITextField. **How we can get the callback for each text entered in RETextItem ?** Please suggest any documentation available for that or any code snippet. Any help is appreciated.

**Comment by aabiabdallah** [comment]
You can use the following methods:

- onBeginEditing
- onEndEditing
- onChange
- onReturn
- onChangeCharacterInRange

**Example:**
`myTextItem.onChange = ^(RETextItem* item) { NSLog(@"Value: %@", item.value); }`

**Comment by ProAjit** [comment]
Thank you @aabiabdallah  !! This worked..!!
